### ISSUE TITLE
Ламы

### ISSUE THREAD

**Issue by FrCln** [sarseniy/infa_2020_sarseniy#1]
Окно маловато - картинка не влезает.
И сделай еще чтобы цветы были разноцветными (при каждом запуске разные) и с разным количеством лепестков. И еще я хочу, чтобы ламы, повернутые в разные стороны, были идентичными с точностью до зеркального отражения.

**Comment by sarseniy** [comment]
> Окно маловато - картинка не влезает.


Расширил, добавил новые элементы на пустое место. Та лама, что выглядывает справа и должна так выглядывать.

> И сделай еще чтобы цветы были разноцветными (при каждом запуске разные) и с разным количеством лепестков. И еще я хочу, чтобы ламы, повернутые в разные стороны, были идентичными с точностью до зеркального отражения.

Добавил цвета, починил отрисовку ламы, больше не прибавляю случайные значения.
