### ISSUE TITLE
Игра "Шарик"

### ISSUE THREAD

**Issue by FrCln** [sarseniy/infa_2020_sarseniy#3]
1. Неужели нельзя было вот это сделать через список?
```python
def play_sound():
    """
    Функция воспроизводит случайный звук при попадании по шарику
    """
    i = randint(1, 3)
    if i == 1:
        pop_sound1.play()
    if i == 2:
        pop_sound2.play()
    if i == 3:
        pop_sound3.play()
```
Понадобилась бы одна строка.

2. Вместо использования отдельных списков `x, y, r, v, alpha, color, type` стоило бы каждую фигуру представить словарем с полями x, y и др., а сами эти словари сложить в один список.

3. Зачем функция `move_balls` принимает параметр num? Она что, сама не может посмотреть, сколько элементов в списке? А что будет, если ей передадут некорректный параметр?

4. Функцию `pygame.display.update()` нужно вызывать один раз после отрисовки всего кадра.

**Comment by sarseniy** [comment]
Fixed

**Comment by FrCln** [comment]
Я имел в виду немного другое. Фигуру представить словарем:
```python
ball = {
    'x' : 10, 'y' : 25, 'type' : 'ball', ...
}
```
А их уже складывать в список:
```python
figures.append(ball)
```
Это даст больше порядка, и потом их будет удобно перебирать в цикле:
```python
for fig in figures:
    if fig['type'] == 'ball':
        ...
```

Да, и ещё вместо ввода имени через консоль хорошо бы сделать это в самом графическом интерфейсе. Это несложно. Нужно просто сделать такой же цикл обработки событий, как и в основной части игры, но обрабатывать события типа KEYDOWN. У этих событий есть поле 'unicode', в котором записан выведенный символ. Нужно только этот символ дописать к строке и отобразить на экране. Отдельно обработать событие нажатия 'Enter' - выход из цикла и начало игры.

**Comment by FrCln** [comment]
И ещё файл records.txt лучше добавить в gitignore, а в программе адекватно обработать ситуацию его отсутствия в папке.

**Comment by sarseniy** [comment]
> Я имел в виду немного другое. Фигуру представить словарем:
> 
> ```python
> ball = {
>     'x' : 10, 'y' : 25, 'type' : 'ball', ...
> }
> ```
> 
> А их уже складывать в список:
> 
> ```python
> figures.append(ball)
> ```

Сделано.

> И ещё файл records.txt лучше добавить в gitignore, а в программе адекватно обработать ситуацию его отсутствия в папке.

Если файлика нет в папке, то программа его автоматически создаст и ошибки не будет. А на Гит я загружаю его, чтобы это была некая статистика для пользователей)

**Comment by sarseniy** [comment]
Closed.
