### ISSUE TITLE
Пушка

### ISSUE THREAD

**Issue by FrCln** [sarseniy/infa_2020_sarseniy#4]
Замечания по коду:
1. Почему количество набранных очков хранится в классе Target? Это нелогично. Функция `update_score` обращается к этому классу, лучше ей просто передать в параметре количество очков. Или, может быть, сделать отдельный класс Score, где все это хранить и обрабатывать. Вообще вся логика обработки попаданий и подсчета очков у вас очень запутана.

2. Название метода set_coords не отражает его смысл. Надо назвать его draw или что-то в этом роде.

3. Также название класса Ball не очень удачно. Это же снаряд. Так его и надо назвать.

4. Рисование в методе `__init__` лишнее, лучше вызвать оттуда соответствующий метод (который сейчас называется set_coords). Атрибут id нигде не используется.

Замечания по самому геймплею.
1. Физика полета снаряда и отражения от стен местами здорово хромает.

2. Новые цели часто появляются на месте только что сбитых и тут же сбиваются тем же снарядом. Надо или уничтожать сам снаряд при попадании, или добавить задержку, или следить, чтобы цели создавались в другом месте. Вариант с задержкой - наиболее интересен с точки зрения программной реализации. :-) 

3. Не хватает `pygame.quit()` в конце. При выходе программа иногда повисает (при запуске в интерактивном режиме).

**Comment by sarseniy** [comment]
> Замечания по коду:

Поправил.

> Физика полета снаряда и отражения от стен местами здорово хромает.

Физику полёта переделал, теперь (вроде бы) не выдаёт ничего неадекватного.

> Новые цели часто появляются на месте только что сбитых и тут же сбиваются тем же снарядом.

Добавил задержку при появлении новых мишеней.

Из следующих задач:

- [ ] Добавить музыку и звуки
- [ ] Реализовать запись результатов в файл
- [ ] Добавить анимации (?)
